/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-122520-gb637624046-20260121"
#endif /* AVUTIL_FFVERSION_H */
